# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retries', models.IntegerField()),
                ('row', models.IntegerField()),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'tool_error_detail',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('log_type', models.CharField(choices=[(b'view', b'view log'), (b'chat', b'chat log'), (b'stream', b'stream log')], editable=False, max_length=8)),
                ('is_finished', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[(b'success', b'success'), (b'warning', b'warning'), (b'failed', b'failed'), (b'waiting', b'waiting')], default=b'waiting', editable=False, max_length=8)),
                ('total_rows', models.PositiveIntegerField()),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('task_time', models.IntegerField(default=0)),
                ('retries', models.IntegerField(default=0)),
                ('retry', models.BooleanField(default=False)),
                ('system_log', models.TextField()),
                ('start_time', models.DateTimeField(editable=False)),
                ('stop_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tool_result',
            },
        ),
        migrations.AlterIndexTogether(
            name='result',
            index_together=set([('file_name', 'created_at')]),
        ),
        migrations.AddField(
            model_name='errordetail',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_storage.Result'),
        ),
        migrations.AlterIndexTogether(
            name='errordetail',
            index_together=set([('result', 'retries', 'row')]),
        ),
    ]
